# ASP.NET Core
# Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.0$(Rev:.r)

parameters:
- name: buildConfig
  displayName: 'Build Config ?'
  type: string
  default: 'Debug'
  values:
  - 'Debug'
  - 'Release'
- name: image
  displayName: 'Pool Image ?'
  default: 'ubuntu-latest'
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger:
- master

stages:
- stage: Build
  displayName: Build Package
  jobs:
    - job: buildNuget
      displayName: 'Build package'
      pool:
        vmImage: ${{parameters.image}}
      variables:
        buildConfiguration: ${{parameters.buildConfig}}
    
      steps:
      # Use latest 3.x sdk
      - task: UseDotNet@2
        displayName: 'Get latest dot net core 3.x'
        inputs:
          packageType: 'sdk'
          version: '3.x'

      # dotnet restore
      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: 'restore'
          projects: '$(Build.SourcesDirectory)/src/Templating.RiotSPA/Templating.RiotSPA.csproj'
          feedsToUse: 'select'
    
      # create nuget package
      - script: dotnet pack $(Build.SourcesDirectory)/src/Templating.RiotSPA/Templating.RiotSPA.csproj -o $(Build.ArtifactStagingDirectory) --no-build
        displayName: 'dotnet pack $(buildConfiguration)'